### PR TITLE
feat: upgrade react to latest version

### LINKED ISSUE #32: React version upgrade
**Description**:
I would like to keep my dependencies up to date.

**AC's**:
- Use latest `react`
- Use latest `react-dom`
- Use latest `react-scripts`
- Use latest `typescript`
- design & functionality is not broken anywhere

### PR DESCRIPTION
**Pull request by ansh-saini**
Fixes #32 
Upgrade React ✅ 
Upgrade Typescript ❌ 

Upgrading typescript to latest is not a good idea right now because MUI v4 does not seem to support it. We can do it after we have migrated to MUI v5
image

### CODE REVIEW

**Comment by merey90** [comment]
Hey @ansh-saini, thanks for contribuiton.
Unfortunately netlify build started breaking with this error:
Screenshot 2022-10-12 at 11 09 12
Can you check?

**Comment by merey90** [comment]
Seems like this is not the Typescript upgrade problem.

**Comment by ansh-saini** [comment]
Okay Ill look into it

**Comment by ansh-saini** [comment]
Okay, apparently MUI v4 is not supported with React 18.
We would have to upgrade MUI along with React as well.

**Comment by merey90** [comment]
Thank you anyway for your support! 👍

**Pull request closed without merging**
